### ISSUE TITLE
Error in executing the command

### ISSUE THREAD

**Issue by MetiCodePrivateLimited** [771979972/paddle-SAM#3]
I am trying to run the following command and getting error:

python3.8 scripts/inference_side_by_side.py --exp_dir=test_inference --checkpoint_path=pretrained_models/sam_ffhq_aging.pdparams --data_path=images --test_batch_size=4 --test_workers=0 --target_age=0,10,20,30,40,50,60,70,80,90,100

Error:

/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
{'exp_dir': 'test_inference', 'dataset_type': 'ffhq_aging', 'input_nc': 4, 'label_nc': 0, 'output_size': 1024, 'batch_size': 6, 'test_batch_size': 4, 'workers': 0, 'test_workers': 0, 'learning_rate': 0.0001, 'optim_name': 'ranger', 'train_decoder': False, 'start_from_latent_avg': False, 'start_from_encoded_w_plus': True, 'lpips_lambda': 0.1, 'id_lambda': 0.1, 'l2_lambda': 0.25, 'w_norm_lambda': 0.005, 'aging_lambda': 5.0, 'cycle_lambda': 1.0, 'lpips_lambda_crop': 0.6, 'l2_lambda_crop': 1.0, 'lpips_lambda_aging': 0.1, 'l2_lambda_aging': 0.25, 'stylegan_weights': 'pretrained_models/stylegan2-ffhq-config-f.pdparams', 'checkpoint_path': 'pretrained_models/sam_ffhq_aging.pdparams', 'max_steps': 500000, 'image_interval': 100, 'board_interval': 50, 'val_interval': 2000, 'save_interval': 4000, 'target_age': '0,10,20,30,40,50,60,70,80,90,100', 'use_weighted_id_loss': True, 'pretrained_psp_path': 'pretrained_models/psp_ffhq_encode.pdparams', 'file_name': None, 'data_path': 'images', 'couple_outputs': False, 'resize_outputs': False, 'n_images': None, 'n_outputs_to_generate': 5, 'mix_alpha': None, 'latent_mask': None, 'ref_images_paths_file': './ref_images.txt'}
Loading SAM from checkpoint: pretrained_models/sam_ffhq_aging.pdparams
Traceback (most recent call last):
  File "scripts/inference_side_by_side.py", line 97, in <module>
    run()
  File "scripts/inference_side_by_side.py", line 35, in run
    net = pSp(opts)
  File "/usr/local/SAM/models/psp.py", line 27, in __init__
    self.load_weights()
  File "/usr/local/SAM/models/psp.py", line 35, in load_weights
    ckpt = torch.load(self.opts.checkpoint_path, map_location='cpu')
  File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 766, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")

**************************
Could you guide me to fix it? 
Thanks

**Comment by sldyns** [comment]
Hello,

Sorry to point out that, you might execute the incorrect code, as the error was throwed by "torch.load". Our project was built totally based on PaddlePaddle, there is no Pytorch code.

Please make sure you are executing the correct code.

Best,
Kun

**Comment by MetiCodePrivateLimited** [comment]
It was error on my side. Fixed. Thanks.
